### ISSUE TITLE
Komme nicht weiter

### ISSUE THREAD

**Issue by d1heller** [CASFEE2014Team9/RedditClone#5]
Ich sehe aktuell - wiedermal - nichts... keine Kategorien, keinen Listeninhalt... einfach nichts. Was hat geändert? Evtl. müssen wir morgen kurz schauen --> Frust!

**Comment by JanEggers** [comment]
du musst vielleicht nur wieder bower install aufrufen ich habe gestern linq.js eingebunden damit ich die posts nach rating sortieren kann. ich gucke mal wie man das errorhandling an der stelle verbessern kann

**Comment by JanEggers** [comment]
ich habe nen errordialog eingebaut der angezeigt wird wenn was nicht gefunden wurde.

**Comment by JanEggers** [comment]
es gibt auch https://www.npmjs.org/package/gulp-shell mit dem könnte man von gulp aus npm install oder bower install aufrufen aber das bring ja irgendwie nichts weil man erstmal das gulp-shell plugin braucht damit das funktioniert.

scheiss plugin scheiss

**Comment by d1heller** [comment]
ich habe "npm install" und "bower install" aufgerufen vorher... daran habe ich gedacht. Aber wenn ich die Page lade, dann kommt irgendein Script- Error...
