### ISSUE TITLE
Änderungen?

### ISSUE THREAD

**Issue by d1heller** [CASFEE2014Team9/RedditClone#6]
Wie kann ich jetzt unser Projekt wieder starten? Das node.js ist weg und ich habe jetzt gerade wiedermal die Situation dass ich nicht starten kann... oder sagen wir ich weiss nicht wie ich die Konfig haben muss.

**Comment by JanEggers** [comment]
ich habe eigentlich die runconfig eingecheckt hatte gehofft das es dann einfach funzt narf....

ich habe das so umgebaut wi wir das in der letzte stunde in der schule hatten node.js ist jetzt server.js

sorry

**Comment by d1heller** [comment]
OK, ich versuchs mal... verwende einfach server.js und schaue was passiert. Danke.

**Comment by d1heller** [comment]
hat geklappt...
