### ISSUE TITLE
add comment, läuft nicht

### ISSUE THREAD

**Issue by d1heller** [CASFEE2014Team9/RedditClone#7]
Kannst Du bitte wieder machen dass das Hinzufügen von Kommentaren wieder funktioniert? Natürlich wenn's geht mit Hilfe des Form das wir neu haben. Ich finde mich noch immer nicht so richtig zurecht in unserem JS Urwald und konnte das irgendwie nicht richtig hinbringen.
Ausserdem habe ich versucht mal unser jQuery-UI Form etwas zu stylen. Aber viel habe ich da nicht wirklich hinbekommen... evtl. schaffst Du das ja. Aber allzu viel Zeit würde ich da nicht mehr investieren.

**Comment by JanEggers** [comment]
ist erledigt war fast oki gab nur nen paar elemente die nicht gefunden wurden und der dialog hat nen refresh ausgelöst da will ich noch mal gucken ob man das auch irgendwie anders vermeiden kann.
