### ISSUE TITLE
Vorgehen

### ISSUE THREAD

**Issue by JanEggers** [CASFEE2014Team9/RedditClone#9]
Hi @ryabrody , @d1heller ,

ich habe mal den yeoman machen lassen und das projekt wieder soweit zusammen geknotet das man mit npm install & npm start sowohl an die spa kommt als auch an das rest api.

wie wollen wir uns die weitere arbeit aufteilen?

ich sehe folgende punkte:

x1. navigationskonzept erstellen

x2. html und controller erstellen 

x2.1 post
x2.2 comment
x2.3 user:   register / login
x2.4 rating evtl.

x3. css

handgestrickt ? was vordefiniertes ? sass / less ?

x4. daten vom server holen / schicken und in repositories abfüllen. 

x4.1 filter und sortier api für get
x4.2 evtl. websockets für datenupdates

x4. würde ich mir gern antun.

cheers jan

**Comment by ryabrody** [comment]
@JanEggers @d1heller aso ich würde mir gerne x2 antun mit Angular. Wir wollen doch immernoch angular verwenden oder?
Zum x3 würde ich als vordefiniertes sass würde bootstrap verwenden. Ausser jemand möchte das ganze von grund auf stylen?

**Comment by JanEggers** [comment]
yep angular ftw

**Comment by JanEggers** [comment]
hi @ryabrody  die erste version vom client repository ist da. ich habe in der app nen beispiel reingepackt wie man sie benutzen kann.

delete, 4.1 und 4.2 fehlen noch.

ausserdem würde ich gerne noch model klassen einfügen mit denen mann daten sinnvoll nachladen kann.

naja auf jeden fall kannste jetzt mal daten anbinden wenn du mit den controllern loslegst.

**Comment by d1heller** [comment]
So, bin auch mal da...
Zu x3. keines Falls möchten wir was "von Grund auf stylen"... daher finde ich die Idee mit SASS und Bootstrap ok.
Ich kann mir mal den x1 vornehmen. Nur habe ich gerade Mühe mir vorzustellen was genau unter "Navigationskonzept erstellen" gemacht werden soll.

**Comment by JanEggers** [comment]
mit navigationskonzept erstellen meine ich wie kommt man in welche ansicht. es muss ja immer eine url da hin geben. 

also sowas wie 
#/login für login 
#/category/sport für posts aus der entsprechenden kategorie
#/user/dummy alle posts vom dummy

hauptsächlich ist halt interressant ob wir mit der einen navigationsleiste auskommen oder ob wir nen mehrstufigen navigationsprozess haben

**Comment by d1heller** [comment]
@ryabrody 
Kannst Du vor Deinen Ferien mal noch das was Du schon mal hast "pushen"? Danke Dir. Schöne Ferien.

**Comment by ryabrody** [comment]
@JanEggers ich hab meine änderungen gepusht. Sorry wollte eigentlich mehr machen aber ich tschegg nicht wie man eine relation von den posts zu den comments usw aufbaut.

**Comment by JanEggers** [comment]
@d1heller 
ich habe die stelle wiedergefunden wo du dein bnav modul einbinden kannst das ist in app.js ab zeile 13 in den eckicken klammern

**Comment by d1heller** [comment]
Brauchen wir wirklich für jeden Post das "Rating" so genau??? Das heisst jedes Rating wird mit Wert und User erfassst?
Ich bin der Meinung es reicht einen Score pro Post zu haben. Wer ein Rating abgibt spielt doch keine Rolle.

**Comment by JanEggers** [comment]
Wir brauchen das nicht. Man würde es in Wirklichkeit wahrscheinlich so machen damit der Anbieter der Site tracken kann wem was gefällt damit er die richtige Werbung bringen kann.

**Comment by ryabrody** [comment]
@JanEggers @d1heller 
Hallo Zusammen
Ich hab mir mal den Neusten Stand gepullt. Ihr habt euch ja richtig ins Zeug gelegt :D. Sieht gut aus.
Beim Rating braucht es doch eine Beziehung zum User, damit ein User pro Post nur 1x raten kann.
Habt ihr noch eine Arbeit für mich? Soll ich die beiden Rubriken "About", "Comments" und "Posts", die ich vor den Ferien eingebaut habe wieder rausnehmen?

**Comment by JanEggers** [comment]
hi @ryabrody  franka die beziehung zwischen rating und user ist da da wird im moment nur noch nichts verriegelt. 

about und comments kannste rausnehmen.
dein posts sieht halt besser aus mir ist immer noch nicht wirklich klar welche css klassen man setzten muss damit das ganze gut aussieht.

ich werde mal nach einer bootstap stylesheet boilerplate suchen wo man sich das abgucken kann was wo gesetzt sein muss.

**Comment by ryabrody** [comment]
@JanEggers 
thx fürs feedback.
In der Dokumentation von Bootstrap (http://getbootstrap.com/components/#panels-basic) kannst du übrigends nachschauen, welche Elemente Bootstrap zur Verfügung stellt. Ein HTML Example ist dann direkt unter der Vorschau.

**Comment by ryabrody** [comment]
@d1heller Bist du gerade am HTML pimpen oder soll ich es mir anschauen?

**Comment by d1heller** [comment]
@ryabrody habe mir gestern nur mal "kurz" waren dann auch 2h was angeschaut. Du darfst natürlich SEHR gerne das HTML stylen!!!

**Comment by ryabrody** [comment]
@d1heller @JanEggers 
Hallo Zusammen.
Ich hab die Website ein bisschen umegstyled. Bezüglich Accessibility habe ich bis jetzt noch nicht viel gemacht. Das hol ich noch nach. Die Seite sieht ein bisschen melonig aus. Ich bin kein Designer hoffe aber ihr könnt damit leben. Das kann man natürlich auch noch ändern :).
Auf jeden fall wollt ich mit gulp die sass files "watchen" aber mit gulp serve hat es immer fehler geworfen. Nach langem Probieren habe ich nun hotfix mässig mit grunt das sass zu css kompiiliert. Konntet ihr bei euch den gulp serve ohne Probleme starten?

**Comment by JanEggers** [comment]
hi leude,

@d1heller , @ryabrody  ich habe mal versucht unittests zum laufen zu kriegen über gulp gehts garnicht und mit dem webstormtestrunner so gerade eben.

ich habe es ausserdem nicht hinbekommen die socket.io libary wegzumocken. laut anleitung sieht es eigentlich richtig aus geht aber trotzdem nicht.

wenn ihr zuviel zeit habt könnt ihr euch das ja auch nochmal ansehen.

**Comment by ryabrody** [comment]
Link Publishing System:
- [x] Erfassen von neuen Links
  Kommentar System:
- [x] Links kommentieren können

User Management:
- [x] Erfassen eines neuen Logins (Name / Password)

Security System:
- [x] Login / Logout
- [x] Kommentare / Links erstellen ist nur möglich falls der User eingeloggt ist.

Rating System (Dominik versucht mal diese Punkte umzusetzen):
- [x] Rating der Kommentare / Links
- [x] Eigenes Rating Rückgängig machen.

Weitere Anforderungen:
- [ ] Domain Objekte sauber in Klassen gekapselt.
- [ ] Layer Architektur auf dem Client.
- [x] Fluides Design
  - [x] Smart-Phone
  - [x] Desktop
- [x] Alle Clients sind synchron mit den Daten auf dem Server (ohne Polling)
- [x] Daten via Templates darstellen

Jan: um die beiden kümmer ich mich
- [x] Aufsetzten und starten soll intuitive sein oder beschrieben sein.
- [ ] Mindestens 3 «sinnvolle» Unit Tests

Code Qualität Anforderung
- [x] Sauberer JavaScript Code / Struktur
- [x] Sauberer CSS Code

**Comment by ryabrody** [comment]
@JanEggers @d1heller 
Ich hab hier nochmals die auflistung der Anforderungen. Die optionalen hab ich mal weggelassen 🙈🙊.
Könnt ihr die Liste auch kurz durchgehn und abhäkelkn, was bereits gemacht ist?
@JanEggers hast du noch was am login geändert? ich kann mich irgendwie nicht mehr einloggen/registrieren

**Comment by JanEggers** [comment]
ich hab mal nen haken gesetzt an

Alle Clients sind synchron mit den Daten auf dem Server (ohne Polling)
Daten via Templates darstellen

Login ging bei mir am Wochenende noch

**Comment by JanEggers** [comment]
sauberen code haben wir auch wenn es nach jshint geht was css angeht weiss ich nicht ob das was csslint da motzt wirklich schlimm ist oder eher ein mann könnte das auch anders machen

**Comment by JanEggers** [comment]
@ryabrody: hi franka login sollte wieder gehen. 

kannst du dir bitte noch anschauen das wir das reditcl[[o]]ne O icon auch als favicon haben.

ausserdem fehlt auch noch der sass zu css compiler fürs gulp

**Comment by ryabrody** [comment]
@JanEggers ja ich hab das noch nicht abgehäkelt (wegen dem sauberen code), weil ich das noch nicht fertig gebracht habe mit dem gulp. Das Favicon ist die Weihnachtskugel im Logo. Weil es ja bald Weihnachten ist 😝. Wenn ich den ganzen Schriftzug nehme, dann kann man den sowieso nicht lesen. Findest du das nicht ok so?

**Comment by JanEggers** [comment]
@ryabrody klar ist das ok bei mir war es noch das default yoman icon und das hätte ich nicht so gut gefunden wenn da noch boilerplate zeug wäre. alles gut.

**Comment by ryabrody** [comment]
@JanEggers hast du den browser cache gelöst?

**Comment by ryabrody** [comment]
@JanEggers ech brengs ned fertig das gulp watch ufdsetze ond s gulpfile.js dass die sass_files/ "gwatched" werded. Ech luege dassi schösch morn de Michael no cha froge. Was esch eigentlech met de pagination? Sell ech die au no pimpe? s donkt mi zwor chli wenig 1 post för 1 siite :). Ech glaube de Ponkt "Login / Logout" chamer den ou abhögle oder?

**Comment by d1heller** [comment]
Ich werde mich mal um das Rating der Kommentare kümmern... evtl. schaff ich es auch noch die Bewertungen wieder rückgängig zu machen...
und evtl. auch noch etwas "clean coding" betreiben.

**Comment by ryabrody** [comment]
@JanEggers 
hay jan. ich habe mal dummy posts erstellt und anschliessend für die dummy posts comments. im comments.json sind die drin aber si werden gar nicht mehr dargestellt. weisst du vielleicht an was das liegen könnte?

**Comment by JanEggers** [comment]
keine ahnung so auf anhieb gucke ich mir mal an

**Comment by JanEggers** [comment]
habs die ids sind teilweise number teilweise string und dann matched da was nicht ich mache mal überall strings draus

**Comment by ryabrody** [comment]
@JanEggers jetzt sehe ich sie wieder 👍
Ich hab noch die formulare vereinheitlicht und das ranking in den comments gestyled und die pagination.

**Comment by JanEggers** [comment]
so leude ich brech zusammen...

ich habe jetzt 4 unittests 3 gehen manuell mit gulp geht keiner.

ich habe noch nen bissl manuell getestet und nun funktionieren die updates alle wieder.

wäre froh wenn ihr die tests bei euch auch mal laufen lassen könnt ob ihr wenigstens aufs gleiche ergebnis kommt und vielleicht habt ihr ja noch ne idee was ich da falsch mache.

**Comment by ryabrody** [comment]
@JanEggers meinst du diese tests?
![bildschirmfoto 2014-12-01 um 08 41 08](https://cloud.githubusercontent.com/assets/954367/5242559/d6f2103c-7935-11e4-8647-6378634ae52b.png)

**Comment by d1heller** [comment]
@ryabrody

**Comment by d1heller** [comment]
@ryabrody 
habe gerade gesehen dass wir für die Login/Logout buttons die gleiche ID benutzen... ist es nicht so dass eine ID nur einmal vorkommen darf/soll?
Ich wollte statt ID einfach CLASS verwenden und habe die SASS- Dateien angepasst. Im application.css ist aber immernoch die ID (#login-btn) vorhanden nachdem ich einmal gulp ausgeführt habe... Hinweis?

**Comment by ryabrody** [comment]
@d1heller du musst gulp starten, dann das file ändern, und dann sollte automatisch das application.css geändert werden. das sass-file musst du aber ändern während dem gulp läuft. hast du das so gemacht?

**Comment by d1heller** [comment]
@ryabrody 
habe ich gerade probiert... funktioniert bei mir aber irgendwei nicht. Warum auch immer... in der Konsole bekomme ich folgenden Output wenn ich etwas in einem *.sass- File ändere:
...
[09:54:22] Starting 'sass'...
[09:54:22] Finished 'sass' after 4.49 ms
[09:54:22] Starting 'sass'...
[09:54:22] Finished 'sass' after 4.46 ms
[09:54:22] Starting 'sass'...
[09:54:22] Finished 'sass' after 2.63 ms

Könnte es sein dass ich noch den "Ruby-Installer" laufen lassen muss? Lets give it a try...

**Comment by ryabrody** [comment]
@d1heller ah ja als windows user muss man glaube ich noch ruby installiere, das ist bei mac bereits dabei. Es sollt ein .ruby-version file im repo haben, da siehst du welche ruby version benötigt wird bzw. vielleicht geht es auch mit einer anderen.

**Comment by d1heller** [comment]
@ryabrody 
naja... irgendwie funktioniert alles nicht... mein "application.css" bleibt IMMER gleich. Bin jetzt also ratlos.

**Comment by ryabrody** [comment]
@d1heller 
oh man eijh. so komplizierts zügs 😩
Jo wers ok för dech wenn ech eifach d änderige wörd mache?
Ech cha etz ou ned grad sege a was das es lid.

**Comment by d1heller** [comment]
@ryabrody 
hmmm... jetzt konnte ich gerade einen "watcher-task" hinzufügen als ich die Datei "application.sass" geöffnet habe. Und dann hat er das "application.css" neu gebuildet...
Evtl. musst Du dann einfach nochmal "drüber", denn irgendwie wird beim "hover" über den Login/Logout der Text schwarz... ich probier noch etwas und würde mich allenfalls nochmals melden.
Danke Trotzdem!!!

**Comment by d1heller** [comment]
Habe noch den "Blank Slate" designed... naja, designed ist übertrieben... habe einfach mal was gemacht. Vielleicht hat jemand von Euch ja noch "Lust" und Zeit das noch etwas attraktiver zu machen.

**Comment by ryabrody** [comment]
@d1heller @JanEggers 
können wir noch den ablauf der präsi festlegen? Hier mein Vorschlag: 
- dominik: 3min Demo 
- franca: 2.5 min html/css ("was ist bei uns besonders" und interessante Lesson Learned)
- jan: 2.5 min nodejs/angual ("was ist bei uns besonders" und interessante Lesson Learned)
- 2min Fragen & Antworten
- 2min Umbau (wtf? ist damit der umbau vom projekt 1 zum projekt 2 gemeint? Hier könnte man allenfalls eine folie vorher nachher machen 😂)

Dominik: Mit Umbau ist gemeint von einer Gruppe zur nächsten... denke ich.
Sonst ist der Ablauf für mich ok... Ich frage mich noch wie der Anfangszustand unserer Page sein soll? Blank? Ohne Einträge? MIt sehr vielen Einträgen?

Franca: Ich denke mit vielen Einträgen wegen Pagination und Kommentaren und während der Präsi ist wahrscheinlich keine Zeit die ganzen Post zu schreiben bis die Pagination aktiv ist. Aber was dir lieber ist.

**Comment by d1heller** [comment]
@JanEggers 
Habe noch das Voting von Posts und Kommentaren etwas angepasst. NEU kann der User sein Voting ändern, einfach nur entweder +1 oder -1 oder neutral (0) und zwar so oft er möchte... Kannst Du meinen letzten Commit mal noch prüfen bitte? Allenfalls noch anpassen... DANKE!

**Comment by ryabrody** [comment]
@JanEggers @d1heller 
hay zäme. Wollen wir das Projekt nun abgeben? Aus meiner Sicht ist es ok. @JanEggers Hast du noch eine extra Anleitung geschrieben für die Installation oder ist die einfach im README? Ich hab die Präsi noch ins Repo getan.

**Comment by d1heller** [comment]
Für mich ist auch ok... habe nichts mehr.
@JanEggers ?
Er ist in den Ferien... ich weiss halt nicht wie häufig er die Mails liest... Warten wir mal bis Mittag, sonst geben wir einfach ab.

**Comment by ryabrody** [comment]
@d1heller @JanEggers 
also ech geb das teil etz ab.

**Comment by d1heller** [comment]
@ryabrody 
Danke!

**Comment by JanEggers** [comment]
@ryabrody  Danke dass du dran gedacht hast.

Ich war schon Total im urlaubsfieber und habe das total verplant.

**Comment by d1heller** [comment]
@JanEggers 
@ryabrody 
Hey Leute!
Unser Miniprojekt war glatt ne 6.0!!! Geile Sache! Danke Euch beiden für die MEGA- Arbeit! Habt Ihr auch schon die Resultate bekommen?
Wünsche ein schöne Weihnachtszeit und später dann einen guten Rutsch ins 2015!

**Comment by ryabrody** [comment]
@d1heller 
@JanEggers 
hay juhuuuuu 🎉🎈!!! ja hab es auch gelesen!! Merci ou vell mol för üchi arbeit !!! 
Schöne Wiehnachte ond rötschid guet !!!

**Comment by JanEggers** [comment]
Hi 
@d1heller @ryabrody  Geile nummer dann klappts ja vielleicht doch noch mit dem Abschluss.

Ich bin im Moment in Hamburg weiss also nicht ob schon was angekommen ist.

Dank euch für die Arbeit und guten Rutsch ins neue Jahr.

MfG Jan

**Comment by d1heller** [comment]
@janeggers
Guckst Du mal im Mail...
